name: Docker Test
on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  filter:
    runs-on: ubuntu-latest
    outputs:
      dockerfiles: ${{ steps.filter.outputs.dockerfiles_files }}
      dockerfiles_changed: ${{ steps.filter.outputs.dockerfiles }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          list-files: json
          filters: |
            dockerfiles:
              - "**/Dockerfile*"

  get-components:
    runs-on: ubuntu-latest
    needs: filter
    steps:
      - uses: actions/checkout@v3
      - id: read-component-payload
        uses: ActionsTools/read-json-action@main
        with:
          file_path: ".github/components-payload.json"
      - id: filter-components
        shell: bash
        run: |
          filtered-components="${{ steps.read-component-payload.outputs.components }}"
          echo "components=$filtered-components" >> $GITHUB_OUTPUT
    outputs:
      components: ${{ steps.filter-components.outputs.components }}

  docker-tests:
    needs: ["filter", "get-components"]
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.get-components.outputs.components) }}
    runs-on: ubuntu-latest
    steps:
      - name: Debug
        if: ${{ matrix.component.enabled && contains(needs.filter.outputs.dockerfiles, matrix.component.dockerfile_path) }}
        run: |
          echo '${{ matrix.component.dockerfile_path }}'
        shell: bash
