name: Docker Test
on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  filter:
    runs-on: ubuntu-latest
    outputs:
      dockerfiles: ${{ steps.filter.outputs.dockerfiles_files }}
      dockerfiles_changed: ${{ steps.filter.outputs.dockerfiles }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          list-files: json
          filters: |
            dockerfiles:
              - "**/Dockerfile*"

  get-binary-step-matrix:
    runs-on: ubuntu-latest
    needs: filter
    steps:
      - uses: actions/checkout@v3
      - id: read-binary-matrix
        uses: ActionsTools/read-json-action@main
        with:
          file_path: ".github/binary-matrix.json"
    outputs:
      matrix: ${{ steps.read-binary-matrix.outputs.binary-steps-matrix.include }}

  docker-tests:
    needs: ["filter", "get-binary-step-matrix"]
    strategy:
      fail-fast: false
      matrix:
        services: ${{ fromJson(needs.get-binary-step-matrix.outputs.matrix) }}
        exclude:
          - binary_name: resource-estimation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Debug
        run: |
          echo '${{ matrix.services.dockerfile_path }}'
        shell: bash
