name: Docker Test
on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  filter:
    runs-on: ubuntu-latest
    outputs:
      dockerfiles: ${{ steps.filter.outputs.dockerfiles_files }}
      dockerfiles_changed: ${{ steps.filter.outputs.dockerfiles }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          list-files: json
          filters: |
            dockerfiles:
              - "**/Dockerfile*"

  get-components:
    runs-on: ubuntu-latest
    needs: filter
    steps:
      - uses: actions/checkout@v3
      - id: read-components-matrix
        run: |
          filtered-components="cat .github/components-payload.json | jq -c '.components[] | select(.prod_released == true)' "
          echo $filtered-components
          echo "components=$filtered-components" >> $GITHUB_OUTPUT
        shell: bash
    outputs:
      components: ${{ steps.read-components-matrix.outputs.components }}

  docker-tests:
    needs: ["filter", "get-components"]
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.get-components.outputs.components) }}
    runs-on: ubuntu-latest
    steps:
      - name: Debug
        if: ${{ matrix.component.enabled && contains(needs.filter.outputs.dockerfiles, matrix.component.dockerfile_path) }}
        run: |
          echo '${{ matrix.component.dockerfile_path }}'
        shell: bash
